WP-4320: Update Docker configuration to merge SSL and non-SSL
WebSpellChecker/wproofreader-docker pull request #13
Opened 2022-07-25 15:20 UTC by KharchenkoMaks

This PR implements a universal docker image that can be configured to be ssl or no-ssl at the container start. 
The starting parameters were replaced by environment variables:
`PROTOCOL`: can be `http` or `https`. If none specified, the default be the one that was specified in `config.ini`
`HOST_NAME`: the name of a host name that will be used for setup of demo samples with WProofreader. This is optional parameter, and if nothing is specified, host name from `config.ini` will be used.
`LICENSE_TICKET_ID`: license ticked id to activate the license

2022-07-27 14:10 UTC, solovyovk commented on DockerfileRedHat
>  	tar -xvf $DeploymentDir/$AppNameMask -C $DeploymentDir/ &&\
ADD has the ability to automatically unpack compressed files. 
If the <src> argument is a local file in a recognized compression format (tar, gzip, bzip2, etc) then it is unpacked at the specified <dest> in the container's filesystem:
`ADD /foo.tar.gz /tmp/`

2022-07-27 19:40 UTC, solovyovk requested changes
Just take a look on my comments here. 
I'm open to discuss all of them.

2022-07-27 19:40 UTC, solovyovk commented on Dockerfile
>  ARG AppNameMask=wsc_app*
if you switch RUN to ADD for "tar" with archive auto unpacking you can probably avoid `AppNameMask`

2022-07-27 19:40 UTC, solovyovk commented on DockerfileCentOS
> +ENV LICENSE_TICKET_ID=""
I think you can use just
`ENV PROTOCOL`
`ENV HOST_NAME`
`ENV LICENSE_TICKET_ID`

2022-07-27 19:40 UTC, solovyovk commented on DockerfileCentOS
>  COPY $FilesDir/* $DeploymentDir/
Do you need an asterisk here?

2022-07-28 14:42 UTC, maxim-voronko commented on DockerfileRedHat
>  	tar -xvf $DeploymentDir/$AppNameMask -C $DeploymentDir/ &&\
I think that if we will use ADD to unpack tar.gz file we will obtain one more layer and then the size of our image will increase... Maksym, you can try this approach, but be careful with result image size... We want to have as smaller image as possible.

2022-07-28 14:53 UTC, maxim-voronko commented on Dockerfile
>  	mv $AppRootDir* $AppRootDir &&\
Before image build we put our last application into files directory. The name of package is something like this:
wsc_app_some_version_here.tar.gz
Then we unpack this tar and have as result next folder -- WSC_some_version_here.
To be independent on package version we do this move --- mv WSC* WSC
After move we have just WSC folder without version and can work with this directory like with WSC directory.
So there is some hack to get rid of version in directory name.

2022-07-29 08:19 UTC, KharchenkoMaks commented on Dockerfile
> +	rm /etc/nginx/sites-enabled/default &&\
`default` is always a file

2022-07-29 08:38 UTC, KharchenkoMaks commented on Dockerfile
> +ENV LICENSE_TICKET_ID=""
I can't use just `ENV PROTOCOL` because I have an error: https://github.com/moby/moby/issues/34806 . But I can use `ENV PROTOCOL=`

2022-07-29 12:41 UTC, KharchenkoMaks commented on Dockerfile
>  ARG WebServerPort=8080
Renamed

2022-07-29 12:42 UTC, KharchenkoMaks commented on Dockerfile
>  RUN	mkdir -p $CustomDictionariesDir && mkdir -p $UserDictionariesDir &&\
Done

2022-07-29 12:42 UTC, KharchenkoMaks commented on DockerfileCentOS
> +ENV LICENSE_TICKET_ID=""
Removed the `""` part, but I can't remove the `=`

2022-07-29 13:15 UTC, KharchenkoMaks commented on DockerfileRedHat
>  	tar -xvf $DeploymentDir/$AppNameMask -C $DeploymentDir/ &&\
Now we are copying all files from `files` directory, and our `.tar.gz` build with appserver too. So we will need to rewrite this code to copy all files except our package, and copy our package by `ADD` command. But do we really need it and does it have some benefits?

2022-07-29 13:16 UTC, KharchenkoMaks commented on Dockerfile
>  COPY $FilesDir/* $DeploymentDir/
We copy all files from `$FilesDir`, not the dir itself.

2022-08-01 13:35 UTC, KharchenkoMaks commented on DockerfileRedHat
>  	tar -xvf $DeploymentDir/$AppNameMask -C $DeploymentDir/ &&\
I have tested it, and I came to the conclusion that this will definitely increase the size of the resulting image by 600-700 MB because `tar.gz` weights 400 MB while unpacked, it weights over 1 GB. So, if we unpack, install and delete the package in one layer, we will lose only 400 MB, not 1 GB.

2022-08-01 16:19 UTC, KharchenkoMaks commented on Dockerfile
> +	rm /etc/nginx/sites-enabled/default &&\
Added `-f`

2022-08-02 14:42 UTC, maxim-voronko commented on Dockerfile
> +ARG languages_to_install=0
Default value for languages_to_install is 1,2

2022-08-02 16:34 UTC, maxim-voronko commented on files/configureWebServer.pl
> +		replaceFileContent('localhost', $host, $nginxConf);
What do you replace here? Please write where and for what we use this localhost.

2022-08-03 08:30 UTC, maxim-voronko commented on DockerfileRedHat
>  	tar -xvf $DeploymentDir/$AppNameMask -C $DeploymentDir/ &&\
I think 600 MB to high prize for elegant ADD command. If there is no way how to use ADD command without increasing size on 600 MB -- then let's use previous approach.....

2022-08-03 09:56 UTC, KharchenkoMaks commented on Dockerfile
> +ARG languages_to_install=0
Changed

2022-08-03 09:58 UTC, KharchenkoMaks commented on files/configureWebServer.pl
> +		replaceFileContent('localhost', $host, $nginxConf);
Add comment and more specific replace expression.

2022-08-04 14:15 UTC, KharchenkoMaks commented on README.md
> +If `license_ticket_id` wes specified during the image creation, you don't need to specify it during the launch of `docker run` command.
Fixed

2022-08-04 22:00 UTC, solovyovk commented on Dockerfile
>  FROM ubuntu
Please, pin the exact version of ubuntu
https://nickjanetakis.com/blog/docker-tip-18-please-pin-your-docker-image-versions

2022-08-04 22:06 UTC, solovyovk commented on DockerfileCentOS
>  	yum install -y epel-release &&\
Keep your code clean and follow DRY principles.

2022-08-04 22:07 UTC, solovyovk commented on DockerfileCentOS
> +	mkdir -p $UserDictionariesDir &&\
Keep your code clean and follow DRY principles.

2022-08-05 10:31 UTC, KharchenkoMaks commented on Dockerfile
>  FROM ubuntu
Done, used `22.04`

2022-08-05 10:31 UTC, KharchenkoMaks commented on DockerfileCentOS
>  	yum install -y epel-release &&\
Fixed

2022-08-05 10:31 UTC, KharchenkoMaks commented on DockerfileCentOS
> +	mkdir -p $UserDictionariesDir &&\
Fixed

2022-09-08 16:04 UTC, merged